### ISSUE TITLE
resource module not available in windows

### ISSUE THREAD

**Issue by realsarm** [Jaymon/pout#68]
`pout` uses `resource` module which is UNIX-specific. Consider using [psustil](https://pypi.org/project/psutil/) which is cross platform.

Using this module on windows results in 
```
Traceback (most recent call last):
  File "C:/Users/User/YandexDisk/myAI/myDL/tensorflow_dnn_classifier_estimator_cloud.py", line 3, in <module>
    import pout
  File "C:\Program Files\Python37\lib\site-packages\pout\__init__.py", line 42, in <module>
    from .interface import (
  File "C:\Program Files\Python37\lib\site-packages\pout\interface.py", line 9, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'
 ```

**Comment by Jaymon** [comment]
This was fixed in [v0.8.17](https://github.com/Jaymon/pout/commit/48fb2b27a1a3da1b49f286dd708f689f068e328a) and above but it looks like I never pushed anything to pypi, sorry about that.

You can install it directly from github:

```
pip install -U "git+https://github.com/Jaymon/pout#egg=pout"
```

And I should have a new version pushed up to pypi shortly also.

You only lose the memory printing by not having resource and I don't think it's worth introducing a third party dependency for just that, I might change my mind if I ever develop on Windows though
